### ISSUE TITLE
PR Branch labeler github action broken

### ISSUE THREAD

**Issue by matks** [PrestaShop/docs#1156]
> Run ffittschen/pr-branch-labeler@v1
(node:1467) UnhandledPromiseRejectionWarning: HttpError: Resource not accessible by integration
    at /home/runner/work/_actions/ffittschen/pr-branch-labeler/v1/node_modules/@octokit/request/dist-node/index.js:66:23
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(node:1467) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:1467) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
Error: Resource not accessible by integration

https://github.com/PrestaShop/docs/pull/1155

**Comment by matks** [comment]
I thought I fixed this in https://github.com/PrestaShop/docs/pull/1146

**Comment by matks** [comment]
Was not applied on 1.7.x

Should be fixed thanks to https://github.com/PrestaShop/docs/pull/1157
