### ISSUE TITLE
The home page is not updated after edit in /my_template/_dev/css/partials/_variables.scss

### ISSUE THREAD

**Issue by stiletto75** [PrestaShop/docs#921]
Hi, i'm a new user and i have version 1.7.7.1 and I'm developing a new template (created copy of the folder included the _dev folder) I launched npm install and after in the file /my_template/_dev/css/partials/_variables.scss I modified $base-font-size and executed webpack to recompile, but the home page is not updated.

The generated errors are as follows:

- npm audit gives me this error: js-yaml <= 3.13.0 Severity: High (I had already installed version 3.13.0)
- (node:39103) DeprecationWarning: Tapable.plugin is deprecated. Use new API on `.hooks` instead
(node:39103) DeprecationWarning: Module.meta was renamed to Module.buildMeta
/usr/share/nodejs/webpack/lib/Chunk.js:151
                throw new Error(ERR_CHUNK_ENTRY);
                ^

Error: Chunk.entry was removed. Use hasRuntime()
    at Chunk.get entry [as entry] (/usr/share/nodejs/webpack/lib/Chunk.js:151:9)
    at /var/www/html/prestashop/themes/my_template/_dev/node_modules/extract-text-webpack-plugin/index.js:201:14
    at Array.filter (<anonymous>)
    at /var/www/html/prestashop/themes/my_template/_dev/node_modules/extract-text-webpack-plugin/index.js:200:37
    at SyncHook.eval [as call] (eval at create (/usr/share/nodejs/tapable/lib/HookCodeFactory.js:17:12), <anonymous>:5:1)
    at SyncHook.lazyCompileHook [as _call] (/usr/share/nodejs/tapable/lib/Hook.js:35:21)
    at Compilation.seal (/usr/share/nodejs/webpack/lib/Compilation.js:1322:23)
    at /usr/share/nodejs/webpack/lib/Compiler.js:675:18
    at /usr/share/nodejs/webpack/lib/Compilation.js:1261:4
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/usr/share/nodejs/tapable/lib/HookCodeFactory.js:24:12), <anonymous>:22:1)
    at AsyncSeriesHook.lazyCompileHook [as _callAsync] (/usr/share/nodejs/tapable/lib/Hook.js:35:21)
    at Compilation.finish (/usr/share/nodejs/webpack/lib/Compilation.js:1253:28)
    at /usr/share/nodejs/webpack/lib/Compiler.js:672:17
    at eval (eval at create (/usr/share/nodejs/tapable/lib/HookCodeFactory.js:24:12), <anonymous>:9:1)
    at /usr/share/nodejs/webpack/lib/Compilation.js:1185:12
    at /usr/share/nodejs/webpack/lib/Compilation.js:1097:9
    at processTicksAndRejections (internal/process/task_queues.js:79:11)

I installed these versions: Debian Unstable (Bullseye/Sid), node V12.21.0, npm 7.5.2, webpack 4.43.0
How can I solve?

**Comment by matks** [comment]
Hello @stiletto75 I am sorry but npm issues are probably related to your very environment, and it's hard to help you. I dont think we can answer this question

I suggest you look on Google and Stackoverflow for error "Error: Chunk.entry was removed. Use hasRuntime()", I can see many web pages linked to it (see https://github.com/webpack/webpack/issues/2764)
